# Generated by Django 5.1.4 on 2025-10-15 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scompras_app.insumo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_solicitud', to='scompras_app.solicitudcompra')),
            ],
            options={
                'unique_together': {('solicitud', 'insumo')},
            },
        ),
        migrations.DeleteModel(
            name='DetalleSolicitudCompra',
        ),
    ]
