# Generated by Django 5.1.4 on 2025-10-09 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0002_remove_seccion_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='secciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
