# Generated by Django 5.1.4 on 2025-10-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0003_seccion_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='usuarios',
        ),
    ]
