# Generated by Django 5.1.4 on 2025-10-09 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0004_remove_seccion_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainsumo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.IntegerField()),
                ('codigo_insumo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=500)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('nombre_presentacion', models.CharField(max_length=500)),
                ('cantidad_unidad_presentacion', models.CharField(max_length=100)),
                ('codigo_presentacion', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
