# Generated by Django 5.1.4 on 2025-10-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0006_producto_subproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='monto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scompras_app.producto'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='subproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scompras_app.subproducto'),
        ),
    ]
