# Generated by Django 5.1.4 on 2025-10-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0007_solicitudcompra_monto_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='monto_estimado',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
